### ISSUE TITLE
Configuration option(s) to control the slicing of an image into smaller chunks

### ISSUE THREAD

**Issue by ialok** [spatial-computing/strabo-text-recognition#7]
> Background

Strabo fails to execute if the image size is large. Issue #6. While splitting the image into smaller chunks will make the pipeline work, we will like to have this option configurable.

> Possible Fix

- Introduce configuration parameters that can enable/disable the slicing of an image
- (or) Split based on certain image threshold(_file size_)
- Configuration parameter(s) to **control the number** of sub-images for _ColorSegmentation_ and _TextDetection_  stages of pipeline

**Comment by zywangzy** [comment]
As of now, one of the solution to issue #6 is splitting the image into small chunks and process each chunk separately with the following pipeline, then merge the results together into one geojson file. The advantage of this solution is it utilize the current code more effectively. 

For this purpose, the prototype of the handler for large images (mainly the splitting of the large image into small chunks) is perfectly compatible with the current version (as you can see in the file `Strabo.Test/TestCommandLineWorker.cs`, the testLocalWMWholeFile method is almost same as `the other test methods, only added the LargeImageHandler method and a for loop to process each chunk, so it's highly feasible to adapt it to additional controlling configuration parameters.

**Comment by ialok** [comment]
Added configuration parameters for the number of slices (row slice, column slice and the overlap between each slice).
